//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stokOtomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satis
    {
        public int ID { get; set; }
        public int UrunID { get; set; }
        public int Adet { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public int PersonelID { get; set; }
        public Nullable<decimal> Indirim { get; set; }
    
        public virtual Personel Personel { get; set; }
        public virtual Urun Urun { get; set; }
        public virtual Musteri Musteri { get; set; }
    }
}
