//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stokOtomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urun()
        {
            this.Satis = new HashSet<Satis>();
        }
    
        public int ID { get; set; }
        public int MarkaID { get; set; }
        public string Ad { get; set; }
        public int Adet { get; set; }
        public decimal AlisFiyat { get; set; }
        public double Kdv { get; set; }
        public decimal SatisFiyat { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
    
        public virtual Marka Marka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satis> Satis { get; set; }
    }
}
